name: docker-build

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

env:
  IMAGE_NAME: jguerreroparkare/test-tema-12
  SHA: ${{ github.sha }}
  BRANCH_NAME: ${{ github.ref_name }}
  DOCKERFILE_PATH: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v2
        with:
            username: jguerreroparkare
            password: ${{ secrets.MI_PTA_DOCKERHUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.SHA }}
            ${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}